### PR TITLE
readme: typo fix

### PR DESCRIPTION
**Pull request by the-j0k3r**
@JeromeMartinez 

I wasn't sure if this was written like so on purpose, since the website navigation also has similar typos in several files. If this is merged Ill fix the website shortly.

### CODE REVIEW

**Comment by kieranjol** [comment]
I would imagine that it was intentional considering that the capitalised letters represent the name of the project `ollistd`.

**Comment by JeromeMartinez** [comment]
@kieranjol is correct, this one is on purpose, exceptionally.
Thanks for taking care about such potential issues, but for this case it is not something to fix.

**Comment by the-j0k3r** [comment]
;) allow me to be the devils advocate! That play on words is not apparent at first glance (maybe consider adding the project `ollistd` name to the page?), it wasn't until I saw this GitHub page I realized that the `ST D` meant the shortened version of the word `standard` even if I find it odd to see it like that, because...
Consider that this is the internet and that despite the seriousness of the project, it may inflect something else entirely, something less than desirable for the native English speakers who may make *unwanted* jokes at the expense, the end result, unwanted attentions.

Or it may just show that the people involved have a really odd sense of humour... The kind of people I would invite to a dinner party ;)

**Comment by JeromeMartinez** [comment]
> allow me to be the devils advocate! 

Divergent opinions are appreciated.

> Or it may just show that the people involved have a really odd sense of humour...

All people around MediaArea are odd :)

> The kind of people I would invite to a dinner party ;)

Hum... [The Dinner game](https://en.wikipedia.org/wiki/The_Dinner_Game)...

***

More seriously, @dericed committed that so I need him in this debate ;-).

**Comment by the-j0k3r** [comment]
> Hum... The Dinner game...

I was not thinking about that type of dinner guest, for the record :smiley_cat: 

> Divergent opinions are appreciated.

Thank... you... :grin:  I guess.. :blush: 

> More seriously, @dericed committed that so I need him in this debate ;-).

On that note, open standards are great especially when they are adopted widely and have a thriving community that drive the project, very hard to achieve that in open source, attracting and keeping capable people, I find this is not so simple.

Its nice to see this kind of initiative, definitively a good thing. :+1:

**Pull request closed without merging**
